/* 
**  mod_clover.c -- Apache sample clover module
**  [Autogenerated via ``apxs -n clover -g'']
**
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "http_log.h"
#include "ap_config.h"
#include "apr_strings.h"

#define LODWORD(ll) (((long long)(ll))&0xffffffff)
#define HIDWORD(ll) ((((long long)(ll))>>32)&0xffffffff)
#define LLP(p) HIDWORD(p), LODWORD(p)

static const char FILTER_NAME[]="CLOVER";

static void *create_config(apr_pool_t *pool, char *x);
static void *merge_config(apr_pool_t *pool, void *in_base, void *in_add);
static void clover_register_hooks(apr_pool_t *p);

typedef struct {
    apr_bucket_brigade *passbb;
    apr_pool_t *subpool;
} filter_context;

typedef struct {
    int param1;
} module_config;

static const command_rec commands_table[] = {
    AP_INIT_TAKE1("Param1", ap_set_int_slot, (void*)APR_OFFSETOF(module_config, param1), OR_ALL, "Parameter #1"),
    {NULL}
};

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA clover_module = {
    STANDARD20_MODULE_STUFF, 
    create_config,         /* create per-dir    config structures */
    merge_config,          /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    commands_table,        /* table of config file commands       */
    clover_register_hooks  /* register hooks                      */
};

static void logging(filter_context *context, request_rec *request, const char *format, ...) {
    va_list vargs;
    const char *message = NULL;

    va_start(vargs, format);
    message = apr_pvsprintf(context->subpool, format, vargs);
    va_end(vargs);

    printf("%s\n", message);
}

static void *create_config(apr_pool_t *pool, char *x) {
    return apr_pcalloc(pool, sizeof(module_config));
}

static void *merge_config(apr_pool_t *pool, void *in_base, void *in_add) {
    module_config *base = (module_config*)in_base;
    module_config *add = (module_config*)in_add;

    module_config *newconfig = apr_palloc(pool, sizeof(module_config));

    return newconfig;
}

static void *init_context(ap_filter_t *f) {
    if ( !f->ctx ) {
        filter_context *context = f->ctx = apr_palloc(f->r->pool, sizeof(filter_context));

        module_config *config = ap_get_module_config(f->r->per_dir_config, &clover_module);

        context->passbb = apr_brigade_create(f->r->pool, f->c->bucket_alloc);
        apr_pool_create(&context->subpool, f->r->pool);
    }

    return f->ctx;
}

static apr_status_t clover_handler(ap_filter_t *f, apr_bucket_brigade *bb) {
    apr_status_t status = APR_SUCCESS;
    apr_bucket *b = NULL;
    apr_bucket *nextbucket = NULL;
    filter_context *context = (filter_context*)f->ctx;

    if ( context==NULL ) {
        context = init_context(f);
        apr_table_unset(f->r->headers_out, "Content-Length");
    }

    // Workaround: It seems that apr_pvsprintf cannot take a 64bit value
    logging(context, f->r, "ENTERING clover_handler (ctx=0x%08x%08x)", LLP(context));

    if ( APR_BRIGADE_EMPTY(bb) ) {
        return APR_SUCCESS;
    }

    for ( b = APR_BRIGADE_FIRST(bb);
          b != APR_BRIGADE_SENTINEL(bb); ) {
        nextbucket = APR_BUCKET_NEXT(b);

        if ( APR_BUCKET_IS_EOS(b) ) {
        }
        else if ( APR_BUCKET_IS_METADATA(b) ) {
        }
        else if ( APR_BUCKET_IS_FLUSH(b) ) {
        }
        else {
        }

        b = nextbucket;
    } // main loop

    status = ap_pass_brigade(f->next, bb);

cleanup:
    apr_pool_clear(context->subpool);

    logging(context, f->r, "LEAVING clover_handler (ctx=0x%08x%08x)", LLP(context));

    return status;
}

static void clover_register_hooks(apr_pool_t *p)
{
    // It's ok to use the 3rd parameter for init_context, but ap_init_context_func cannot be used
    // to update the value of Content-Length from. Content-Length should be updated from the
    // first call of handler. This means that we need to check the context is NULL or not
    // before the main loop in handler.  In this case, it's simpler to call init_context from
    // handler directly and not to use ap_init_context_func here.
    ap_register_output_filter(FILTER_NAME, clover_handler, NULL, AP_FTYPE_RESOURCE);
}

